package codes

var zhCNText = map[int]string{
	SUCCESS:                "OK",
	FAILURE:                "FAIL",
	NotFound_404:           "资源不存在",
	RequestsFrequently:     "请求过多",
	InvalidParameter:       "参数错误",
	AuthorizationError_403: "暂无访问权限",
	InvalidToken_401:       "无效的token",
	CaptchaErr:             "获取验证码失败，请稍后重试.",
	CaptchaVerifyErr:       "验证码错误",
	PhoneExistErr:          "手机号已存在",
	EmailExistErr:          "邮箱已存在",
	UserNotExist:           "当前账号不存在，请先注册",
	UserLock:               "当前账号被冻结",
	PwdNotExist:            "尚未设置密码，请选择验证码登录",
	ThirdNotScan:           "未收到扫描信息",
	ThirdExpire:            "已过期",
	ErrRePassword:          "重复密码不一致",
	ErrPasswordFMT:         "密码长度必须6位",
	ErrMobileOrEmail:       "必须手机号或者邮箱注册",
	ErrVerifyCode:          "验证码错误",
	ErrBind:                "绑定失败",
	ErrUserExist:           "账号已经注册，请直接登录",
	ErrUsernameOrPwd:       "账号或者密码错误",
	ErrPwd:                 "密码错误",
}
