package codes

var enUSText = map[int]string{
	SUCCESS:             "OK",
	FAILURE:             "FAIL",
	NotFound:            "resources not found",
	RequestsFrequently:  "Too many requests",
	InvalidParameter:    "Parameter error",
	AuthorizationError:  "You have no permission",
	NotLogin:            "Please login first",
	InvalidToken:        "Invalid Token",
	CaptchaErr:          "Get captcha fail,Please try again later",
	CaptchaVerifyErr:    "Verification code error",
	PhoneExistErr:       "Phone already exists",
	EmailExistErr:       "Email already exists",
	ErrToken:            "Token失效",
	ErrNoToken:          "登录用户才能访问",
	ErrNoAccessRights:   "没有访问权限",
	ErrUseLimitUser:     "您不在访问授权时间内",
	ErrUserNotExist:     "当前账号不存在，请先注册",
	ErrUserLock:         "当前账号被冻结",
	ErrPwdNotExist:      "尚未设置密码，请选择验证码登录",
	ErrMealLimit:        "成员数已达到套餐的限制，请升级套餐重试",
	ErrAccessApplyExits: "您已经提交了登录申请，请耐心等待上级授权，通过授权即可登录",
	ErrMpNotScan:        "未收到扫描信息",
	ErrMpExpire:         "已过期",
	ErrRePassword:       "重复密码不一致",
	ErrPasswordFMT:      "密码长度必须6位",
	ErrMobileOrEmail:    "必须手机号或者邮箱注册",
	ErrParams:           "参数错误",
	ErrVerifyCode:       "验证码错误",
	ErrUnLogin:          "未登录",
	ErrNotSelectCompany: "未选中企业",
	ErrBind:             "绑定失败",
	ErrUserExist:        "账号已经注册，请直接登录",
	ErrRoleOnePerm:      "至少选择一项权限",
}
